### ISSUE TITLE
Options does not appear, or opacity not updated

### ISSUE THREAD

**Issue by german970814** [enesozturk/react-native-hold-menu#37] opened 2021-07-21 00:13 UTC
**Describe the bug**
Sometimes the options opacity seems like does not work properly

**To Reproduce**
Create a component and wrapper your component inside HoldItem. If your component is using React.memo, text in options is never shown

**Expected behavior**
Text shown

**Actual behavior**
Text doesnt shown

**Screenshots**
![image](https://user-images.githubusercontent.com/15973868/126410566-4cb5b53e-4cd7-4708-be3b-7059e3847cde.png)

**Package versions**
 - React: 16.13.1
 - React Native: 0.63.4
 - React Native Reanimated: 2.1.0
 - React Native Hold Menu: 0.1.0
 - Expo: 41.0.1

**Additional context**
Some of my code:

```
const GalleryItem: React.FC<{
  own?: boolean;
  index: number;
  item: Gallery;
  onPress: () => void;
}> = ({ own, index, onPress, item }) => {
  const { deletePublicImage } = useGalleryActions();

  const onDelete = React.useCallback(() => {
    deletePublicImage({ uid: item.id });
  }, [item.id]);

  const MenuItems = React.useMemo(
    () => [
      {
        text: "Eliminar",
        onPress: onDelete,
        isDestructive: true,
      },
    ],
    [onDelete]
  );

  return (
    <HoldItem items={MenuItems}>
      <View
        style={{
          aspectRatio: 1,
          width: (width - 40) / 2,
          marginLeft: index % 2 === 0 ? 10 : 0,
          marginRight: index % 2 === 0 ? 15 : 0,
        }}
      >
        <Pressable onPress={onPress} style={{ width: "100%", height: "100%" }}>
          <Image style={styles.img} source={{ uri: item.media }} />
        </Pressable>
      </View>
    </HoldItem>
  );
};
```

To be clear, if I define my GalleryItem with React.memo, then text opacity is never updated. Otherwise, sometimes appears and sometimes doesnt

**Comment by enesozturk** [comment] 2021-08-07 13:29
Hi @german970814, did you able to fix this issue? I could not reproduce it with almost same usage. Also memoized my components;

<details>
<summary>GalleryItem.tsx</summary>

```js
import React, { useMemo, memo } from 'react';
import { StyleSheet, View } from 'react-native';
import { HoldItem } from 'react-native-hold-menu';

interface GalleryItemProps {}

const GalleryItem = ({}: GalleryItemProps) => {
  const onDelete = React.useCallback(() => {
    console.log('delete Item');
  }, []);

  const galleryItemMenu = useMemo(
    () => [
      {
        text: 'Eliminar',
        onPress: onDelete,
        isDestructive: true,
      },
    ],
    []
  );

  return (
    <HoldItem items={galleryItemMenu} menuAnchorPosition="top-left">
      <View style={styles.item} />
    </HoldItem>
  );
};

export default memo(GalleryItem);

const styles = StyleSheet.create({
  item: {
    width: 100,
    height: 100,
    backgroundColor: 'gray',
  },
});

```

</details>

<details>
<summary>Gallery.tsx</summary>

```js
import React, { memo } from 'react';
import { StyleSheet } from 'react-native';

import GalleryItem from './GalleryItem';

interface GalleryProps {}

const Gallery = ({}: GalleryProps) => {
  return <GalleryItem />;
};

export default memo(Gallery);

```

</details>

And result is like:

https://user-images.githubusercontent.com/19428358/128596973-87fdf5c8-016f-4b1d-924c-9ad9f7065a42.mov

**Comment by german970814** [comment] 2021-08-07 14:54
Hi @enesozturk I was not able to solve that. So I decided to uninstall this package

**Comment by enesozturk** [comment] 2021-08-15 13:06
Closing for now.

**Closed by enesozturk** 2021-08-15 13:06 UTC
Labels: bug
