### ISSUE TITLE
Error: Unable to resolve module @unimodules/core

### ISSUE THREAD

**Issue by crzycoder** [enesozturk/react-native-hold-menu#54] opened 2021-12-09 11:45 UTC
<img width="571" alt="Screenshot 2021-12-09 at 4 45 05 PM" src="https://user-images.githubusercontent.com/43851308/145390719-22a5e390-585e-464d-9769-cf32bf1f8682.png">

**Comment by enesozturk** [comment] 2021-12-31 07:11
Hi, this is a duplicate of https://github.com/enesozturk/react-native-hold-menu/issues/9 you may need the check installation steps for unimodules. This package uses expo-haptic out of the box.

**Closed by enesozturk** 2021-12-31 07:11 UTC
Labels: bug

**Comment by Pyroboomka** [comment] 2022-05-30 12:19
I guess you can reopen this, because unimodules are dead, and I get the same error trying to use this package with expo-modules installed.

https://github.com/expo/fyi/blob/main/expo-modules-migration.md
https://docs.expo.dev/bare/installing-expo-modules/

**Comment by Pyroboomka** [comment] 2022-05-30 14:05
NVM, bumped to 0.1.3, added expo-blur and expo-haptics to my project, it fixed itself.
