### ISSUE TITLE
Multiple Hold Menus In FlatList not retaining passed Ids

### ISSUE THREAD

**Issue by markmccoid** [enesozturk/react-native-hold-menu#4] opened 2021-03-07 05:21 UTC
**Describe the bug**
Not sure if this is a bug or me doing something wrong.

I have a flatlist and the render method outputs a tile wrapped by the HoldItem component.  Each of these tiles has a unique ID and when I create a menu to act on that tiles ID, the ID of the first tile I use the Hold Menu on, is the ID that is shown for every tile that I subsequently try to the Hold Menu on.

I'm creating the Menu items with a function that accepts the a Nav function and the Movie ID:

```javascript
const createMenuItems = ({ navigateToDetails, movieId }) => [
  { text: "Actions", isTitle: true, onPress: () => {} },
  {
    text: "Details",
    onPress: () => {
      console.log("movieId in menu", movieId);
      navigateToDetails();
    },
  },
  {
    text: "Action 2",
    withSeperator: true,
    onPress: () => {
      console.log(movieId);
    },
  },
  {
    text: "Delete",
    isDestructive: true,
    onPress: () => {
      deleteMovie(movieId);
    },
  },
];
```

This is the component using the Hold Menu:
```javascript
    <View style={styles.movieCard}>
      {/* <TouchableOpacity
        onPress={navigateToDetails}
        onLongPress={() => setMovieEditingId(movie.id)}
      > */}
      <HoldItem items={menuItems}>
        <View>
          <PosterImage
            uri={movie.posterURL}
            posterWidth={posterWidth}
            posterHeight={posterHeight}
            placeholderText={movie.title}
            style={{ borderRadius: BORDER_RADIUS }}
          />
        </View>
      </HoldItem>
      {/* </TouchableOpacity> */}
      {/* Icon row */}
    </View>
```
Thanks for any insight into the issue.

**Comment by enesozturk** [comment] 2021-03-07 09:17
Hi @markmccoid, thanks for the feedback. I reproduced your problem and trying to solve. It is important point to be able to use hold menu with lists. Will let you know 👍🏽

**Comment by enesozturk** [comment] 2021-03-07 10:55
Looks like it is solved but needed to be add new props for hold menu to keep it performant. In your usage, you may need to wait for new release..

**Comment by markmccoid** [comment] 2021-03-08 04:02
Thanks! I will keep an eye out for a new release.

**Comment by enesozturk** [comment] 2021-03-08 21:28
Ability to pass different menu item action params per item is added by setting a `actionParams` prop. This is merged and will be available for the next release. Thanks @markmccoid 👌🏽

**Closed by enesozturk** 2021-03-08 21:28 UTC
Labels: bug
